#import data set
t<-read.csv("C:/Users/Laurel Cook/Documents/Descriptive STATS Fall 2018/Copy of Education table.csv", stringsAsFactors = F)
#structure of the data
str(t)
#variable name (to change variable from character to numeric)
names(t)
t$High.school.graduate<-as.numeric((t$High.school.graduate))
t$Associate.s.degree..academic<-as.numeric(t$Associate.s.degree..academic)
t$Bachelor.s.degree<-as.numeric(t$Bachelor.s.degree)
t$Master.s.degree<-as.numeric(t$Master.s.degree)
t$Doctoral.degree<-as.numeric(t$Doctoral.degree)
#mean
mean(Copy_of_Education_table$`High school graduate`)
mean(Copy_of_Education_table$`Associate's degree, academic`)
mean(Copy_of_Education_table$`Bachelor's degree`)
mean(Copy_of_Education_table$`Master's degree`)
mean(Copy_of_Education_table$`Doctoral degree`)
#median<
str(Copy_of_Education_table)
median(Copy_of_Education_table$`High school graduate`)
median(Copy_of_Education_table$`Associate's degree, academic`)
median(Copy_of_Education_table$`Bachelor's degree`)
median(Copy_of_Education_table$`Master's degree`)
median(Copy_of_Education_table$`Doctoral degree`)
summary(t$High.school.graduate)
#Create mode (Do this for all 5 variables)
mode_HighSchool<-table(as.vector(t$High.school.graduate))
names(mode_HighSchool[mode_HighSchool==max(mode_HighSchool)])
View(mode_HighSchool)

aa<-table(as.vector(t$High.school.graduate))
names(aa[aa==max(aa)])

hs<-table(as.vector(t$High.school.graduate))
names(hs[hs==max(hs)])
aa<-table(as.vector(t$Associate.s.degree.academic))
names(aa[aa==max(aa)])
ba<-table(as.vector(t$Bachelor.s.degree))
names(ba[ba==max(ba)])+
ma<-table(as.vector(t$Master.s.degree))
names(ma[ma==max(ma)])
do<-table(as.vector(t$Doctoral.degree))
names(do[do==max(do)])

sd(t$High.school.graduate)
var(t$High.school.graduate)
hist(t$Doctoral.degree, xlab="Doctoral Degree", ylab="Number of Degrees")
barplot(t$Doctoral.degree)
boxplot(t$Doctoral.degree)
